
server.port=8081

# ================= MACHINE CONFIG =================

machine.config.path=C:/IHMS_2/Bin/VertexHL7/machine-config.json

# ================= HL7 TCP =================
hl7.tcp.socket-timeout=700000
server.tomcat.connection-timeout=60000

spring.mvc.async.request-timeout=60000
# ================= LIS API =================
#lis.api.connect-timeout=5000
#lis.api.read-timeout=10000
lis.api.connect-timeout=1000000
lis.api.read-timeout=1200000
# ================= LOGGING =================
logging.level.root=INFO
logging.level.com.dxc700au.hl7=DEBUG

# ================= JACKSON =================
spring.jackson.default-property-inclusion=non_null

# ================= SERVER =================
server.error.include-message=always
server.error.include-binding-errors=always

# ================= THREAD SETTINGS =================
spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=100